### ISSUE TITLE
The subtle danger of Timelocks

### ISSUE THREAD

**Issue by dic0de** [EkuboProtocol/governance#16]
In 2021, Compound identified a bug resulting in loss of rewards but because of their week long time-lock delay, it meant that the bug could only be patched after a week and it therefore existed for an entire week with everyone knowing the existence of the bug as expressed here: https://cointelegraph.com/news/compounding-problems-65m-more-comp-at-risk-as-devs-wait-for-time-locked-bug-fix

With this, I am putting forth the following code enhancement for the Timelock contract:
Track and execute voting proposals with two mechanisms
1. The Normal Track where normal voting and normal delay periods are exercised 
2. Critical Track where voting period is shortened and the delay period is as well shortened.
So if Let's say the normal voting period is 48hrs with a delay of 48hrs, The critical track should be something like 6hrs of voting and 1hr of delay. 
The timelock contract can have tags to track which type of voting is done as per a certain proposal, we can use `Enum` for this. 

Kindly review this if it is something the team can consider and I can happily see to it :)

**Comment by moodysalem** [comment]
I don't know if 48h actually would have helped with that specific issue

And critical track would probably need much higher thresholds to be safe, which are really hard to coordinate

Could this be something handled downstream? E.g. two separate governors that have different roles?

**Comment by dic0de** [comment]
Absolutely, 
It is possible to have two Governors, one that handles critical track with shorter time-frame and delay and then have a tradeoff with the execution timeline of the time-lock contract. Yes this can work as well.

**Comment by moodysalem** [comment]
I think separating out ownership roles is the correct solution, but out of scope for this contract because that's both easily handled closer to the owned contract and also more simple (e.g. the owned contract could have the roles embedded such as pauser, fee recipient, etc.)
