### ISSUE TITLE
more unit testing of the token contract

### ISSUE THREAD

**Issue by moodysalem** [EkuboProtocol/governance#2]
need a lot more testing around the delegation functions, which were whipped up in a hurry

**Comment by lambda-0x** [comment]
i would like to help with this, do you have any specific edge cases that you want to test?

**Comment by moodysalem** [comment]
> i would like to help with this, do you have any specific edge cases in mind that you want to get tested?

Would love some help, don't have specific edge cases in mind but reviewing test coverage and filling in blanks would be helpful

**Comment by lambda-0x** [comment]
okay, will go through the contract and think about what kind of tests could be added during the weekend.

**Comment by VictorONN** [comment]
This still up for grabs?

**Comment by moodysalem** [comment]
> This still up for grabs? Am looking for Cairo tasks

Reviewing and testing the code always helpful, but closing this because it's too vague
