### ISSUE TITLE
delegated token

### ISSUE THREAD

**Issue by moodysalem** [EkuboProtocol/governance#47]
staker is low level and allows one-to-many staking

fungible staked token can be higher level but simpler--each address only delegates to a single address

**Comment by moodysalem** [comment]
this could also serve the purpose of measuring each users' share of the total staked tokens over time, or that could be separate

if in the same contract:
- other contracts can cheaply compute the percent of total staked tokens a user had over a period
- but they must take custody at the beginning and end of the period anyway, or...
- the contract should store a list of snapshots a la the staker

if we store a list of snapshots in this fungible staked token, then the share of total staked tokens over any period can be computed externally without taking custody of the staked token

**Comment by moodysalem** [comment]
actually think this still has to be separate

**Comment by AngelicaOvesdotter** [comment]
![image](https://github.com/user-attachments/assets/c5e21dc3-67f1-4c2d-8718-7e23854abb23)

**Comment by AngelicaOvesdotter** [comment]
![Uploading image.png…]()

**Comment by AngelicaOvesdotter** [comment]
``
